spring.application.name=module2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/HP/OneDrive/Documents/tutorialD/db
spring.datasource.username=omDB
spring.datasource.password=om123
spring.jpa.hibernate.ddl-auto=create
